repos:
  - repo: local
    hooks:
      - id: prettier
        name: validate formatting
        language: system
        files: \.(js|html|md|scss)$
        entry: |
          bash -c 'npm run fix:prettier "${@}"' --
        stages: [pre-commit]
      - id: run-sass
        name: minify css with sass
        language: system
        file: \.(scss)$
        entry: |
          bash -c 'npm run gen:minify'
        stages: [pre-commit]
