name: Build spindrift pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      matched-files: ${{ steps.diff-files.outputs.matched-files }}
      nopush: ${{ steps.check-commit.outputs.nopush }}
    steps:
      - name: Checkout site
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check files
        id: diff-files
        # Breakdown of this oneliner:
        # > git log HEAD^1..HEAD --raw --no-decorate --name-only --pretty=oneline
        #   This returns us some output that looks like this:
        #
        #     <COMMIT_HASH> <COMMIT_MESSAGE>
        #     dir/changed_file1
        #     dir/changed_file2
        #     _posts/post.yaml
        #     ...
        #
        # > tail -n +2
        #   Returns the output above, with the initial commit hash/message line removed:
        #
        #     dir/changed_file1
        #     dir/changed_file2
        #     _posts/post.yaml
        #
        # > sed -n '/_posts/p'
        #   Returns only those lines that contain `_posts`. We don't use the more obvious
        #   `grep` here as it exits non-zero when it fails to find a match, and github
        #   actions run by default with `set -o pipefail`, meaning even though our last
        #   step of `wc -l` would return 0 in cases where this step returns no output, the
        #   entire command would fail:
        #
        #     _posts/post.yaml
        #
        # > wc -l
        #   Counts the lines in the output:
        #
        #     1
        #
        # This is then set as output for this step. This step could alternatively check the
        # result of this command and set either ${{ true }} or ${{ false }} as the output,
        # allowing the if in the next step to use the output value directly. The outcome is
        # the same though.
        run: echo "matched-files=$(git log HEAD^1..HEAD --raw --no-decorate --name-only --pretty=oneline | tail -n +2 | sed -n -r '/posts|(.*\.html)|(.*\.css)|workflows|src|assets/p' | wc -l)" >> $GITHUB_OUTPUT

      - name: Check commit
        id: check-commit
        run: |
          MESSAGE=$(git log -1 --format=%s)
          SCOPE=$(echo "${MESSAGE}" |sed -n 's/^[^ (]*(\([^)]*\)).*/\1/p')
          echo "## Preflight"
          echo "Detected scope: **\`${SCOPE}\`**" >> $GITHUB_STEP_SUMMARY

          if [ ${SCOPE} = 'nopush' ]; then
            echo "nopush=true" >> $GITHUB_OUTPUT
          else
            echo "nopush=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-changes.outputs.matched-files != '0' && needs.check-changes.outputs.nopush == 'false' }}
    steps:
      - name: Start summary
        run: echo "## Build Spindrift Pages" >> $GITHUB_STEP_SUMMARY

      - uses: actions/checkout@v6

      - name: Get latest spindrift tag
        id: get-latest-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: zthart/spindrift

      - name: Report tag
        run: |
          echo "Spindrift at version **\`${{ steps.get-latest-tag.outputs.tag }}\`**" >> $GITHUB_STEP_SUMMARY

      - name: Download spindrift
        uses: ash-shepard/fetch-gh-release-asset@v1.0.0
        with:
          repo: hearthsinger/spindrift
          file: spindrift
          version: tags/${{ steps.get-latest-tag.outputs.tag }}

      - name: Run spindrift
        run: |
          chmod +x spindrift
          echo "### Spindrift build summary" >> $GITHUB_STEP_SUMMARY
          mkdir -p blog
          ./spindrift -t _spindrift_templates -c _spindrift.yaml -s posts -o blog | tail -n 6 >> $GITHUB_STEP_SUMMARY

      - name: Update find+replace targets
        run: |
          SHORT_HASH=$(git rev-parse --short=8 HEAD)
          SHORT_DATE=$(date +%F)
          find . -type f -name "*.html" -exec sh -c "sed -i s/BUILD_INFO/${SHORT_HASH}/g {}" \;
          find . -type f -name "*.html" -exec sh -c "sed -i s/BUILD_DATE/${SHORT_DATE}/g {}" \;

      - name: Upload to neocities
        env:
          NEOCITIES_USER: strawbs-dot-io
          NEOCITIES_PASS: ${{ secrets.NEOCITIES_PASS }}
        run: |
          files=()
          clean=()
          echo "# Neocities Batch Upload" >> $GITHUB_STEP_SUMMARY
          echo "Searching for files" >> $GITHUB_STEP_SUMMARY
          echo "## Discovered Files" >> $GITHUB_STEP_SUMMARY

          while IFS= read -r file; do
            remote_path="${file#./}"
            files+=("-F" "${remote_path}=@${file}")
            clean+=("${remote_path}")
          done < <({ find blog/ -type f; find assets/ -type f; find src/ -type f; find . -maxdepth 1 -type f -name "*.html"; find . -maxdepth 1 -type f -name "*.ico"; find . -type f -name "*.min.css"; })
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${clean[@]}" | tr ' ' '\n' | pr -4 -t -w 120 >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          echo "## Upload Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          curl -sS -H "Authorization: Bearer ${NEOCITIES_PASS}" ${files[@]} "https://neocities.org/api/upload" | tail -n 4 >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
